# ===============================
# Configuração principal do Netlify
# ===============================

[build]
  publish = "."
  command = "npm run build"

# Redirecionamento SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ===============================
# Plugin: Cloudinary (para imagens)
# ===============================
[[plugins]]
  package = "netlify-plugin-cloudinary"
  [plugins.inputs]
    cloudName = "aguiasvitrine"

# Variáveis de ambiente são gerenciadas pelo painel Netlify
