[build]
  publish = "."
  command = "npm run build"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
    # Substitua pelos valores reais do seu Cloudinary
    cloudName = "aguiasvitrine"
    apiKey = "SUA_API_KEY_AQUI"
    apiSecret = "SEU_API_SECRET_AQUI"
