[build]
  publish = "."
  command = "npm run build || echo 'Build simples sem npm'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cloudinary"
  [plugins.inputs]
    cloudName = "aguiasvitrine"

[functions]
  directory = "netlify/functions"

[build.environment]
  SUPABASE_URL = "https://qjneiombtvifibolfvel.supabase.co"
  SUPABASE_KEY = "sb_publishable_dMX4SFx5Xaf9EjZXaTH_ug_mohAqyP5"
