[build]
  publish = "."
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cloudinary_aguiasvitrine"
  [plugins.inputs]
    cloudName = "your_cloudinary_cloud_aguiasvitrine"
